# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.15.0

pipelines:
  custom:
    dev-deploy:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install
            - npm run build
            - node deploy $DEV02_HOST $DEV02_USER $DEV02_PASSWORD
            