version: 2.1
jobs:
  deploy_dev_02:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Installation
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy on DEV02
          command: npm run deploy $DEV02_HOST $DEV02_USER $DEV02_PASS
workflows:
  version: 2.1
  build:
    jobs:
    - deploy_dev_02:
        filters:
          branches:
            only:
            - $DEV02_BRANCH